version: '3.8'
services:

  web:
    build: ./
    command: /bin/sh -c "python manage.py migrate
              && python manage.py runscript filldata
              && python manage.py runserver 0.0.0.0:8000"
    environment:
      SQL_HOST: pg
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    depends_on:
      - pg
    env_file:
      - ./.env.dev

  pg:
    image: postgres:13
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - 5433:5432
